### ISSUE TITLE
Class attribute error during multi-sample run

### ISSUE THREAD

**Issue by Krannich479** [vpc-ccg/pamir#24]
Hi,
I am getting the following error when I try to run Pamir:

```
Creating a new project folder... OK
Checking binary pre-requisites...  ... OK
Sorting bam file... SKIPPING
Extracting FASTQ from Alignment file... SKIPPING
Masking Reference Genome... OK
Traceback (most recent call last):
  File "/path/to/pamir/pamir.py", line 1448, in <module>
    sys.exit(main())
  File "/path/to/pamir/pamir.py", line 1438, in main
    run_command(config)
  File "/path/to/pamir/pamir.py", line 1005, in run_command
    index(config)
  File "/path/to/pamir/pamir.py", line 327, in index
    cmd           = pipeline.mrsfast + ' --index  {0} --ws {1}'.format(input_file, config.get("mrsfast","window_size") )
AttributeError: class pipeline has no attribute 'mrsfast'
```

and indeed [class pipeline](https://github.com/vpc-ccg/pamir/blob/fe2396bcca05cd41267f1751b9bab5443cb9b1ef/pamir.py#L18) has no such attribute.

My call was:
```
/path/to/pamir/pamir.py
    -p /path/to/workdir/results
    -r /path/to/genome_ins.fa
    --files mrsfast-best-search=/path/to/workdir/sorted_bams/
```

Can you tell what's going on here? Is the call valid? Input bams are name-sorted.

(Mabye important) Sidenote: The folder **/path/to/workdir/sorted_bams/** does not really contain mappings from mrsFast but BWA. I was told ages ago that *--files mrsfast-best-search* can also handle BWA bam files, please correct me if I am wrong here.

I also tried a run with *--files alignment=\<aln1\>.bwa,\<aln2\>.bwa,...,\<alnN\>.bwa* but that one never started. I am trying to call something like your README's example (2) or (3). 

Thanks!

**Comment by Krannich479** [comment]
I think I can close this anyway since the CLI got a general makeover.
